# -*- coding: utf-8 -*-
"""TimesModel_setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K1BNDDVKWLPY9zmW29QO4Ab73qTIkUk-
"""

!git clone 'https://github.com/leekyuyoung20230313/1.team.git'

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/1.team/TimsNet'

!python 'times_traintest.py' --train_path '/content/1.team/TimsNet/sample_data/s_train1.csv' '/content/1.team/TimsNet/sample_data/s_train2.csv' --val_path '/content/1.team/TimsNet/sample_data/s_val1.csv' '/content/1.team/TimsNet/sample_data/s_val2.csv' --test_path '/content/1.team/TimsNet/sample_data/s_test1.csv' '/content/1.team/TimsNet/sample_data/s_test2.csv' --lr 0.001 --epochs 1 --batch_sizes 2

import pandas as pd
result = pd.read_csv('/content/1.team/TimsNet/results.csv')
result